import Impact_Arrays as imp

#Establishment Nuts and Wood (values are placeholders can = list generated by pdf set generator)
nw_pesticide_application_ha_tree = .05
nw_pesticide_kgai_tree = .012
nw_urea_kgN_tree = .28

nut_estab_impact = nw_pesticide_application_ha_tree * imp.pesticide_application_impact_dict + \
    nw_pesticide_kgai_tree * imp.pesticide_impact_dict + \
    nw_urea_kgN_tree * imp.urea_impact_dict


#Establishment Hay
hay_Nfertilizer_kg_tree = .25
hay_P2O5fertilizer_kg_tree = .64
hay_potassium_chloride_kg_tree = .41
hay_tillage_ha_tree = .0083
hay_petrol_seed_delivery_kg_tree = .2
hay_grass_seed_kg_tree = .25
hay_mowing_ha_tree = .099
hay_pesticide_application_ha_tree = .033

hay_estab_impact = hay_Nfertilizer_kg_tree * imp.N_fertilizer_impact_dict + \
    hay_P2O5fertilizer_kg_tree * imp.phosphate_fertilizer_impact_dict + \
    hay_potassium_chloride_kg_tree * imp.potassium_chloride_fertilizer_impact_dict + \
    hay_tillage_ha_tree * imp.tillage_impact_dict + \
    hay_petrol_seed_delivery_kg_tree * imp.petrol_impact_dict + \
    hay_grass_seed_kg_tree * imp.grass_seed_impact_dict + \
    hay_mowing_ha_tree * imp.mowing_impact_dict + \
    hay_pesticide_application_ha_tree * imp.pesticide_application_impact_dict


#Establishment Total
total_estab_impact = hay_estab_impact + nut_estab_impact


#Nut and Wood Production
nw_prod_pesticide_application_ha_tree = .41
nw_prod_pesticide_kg_tree = .12
nw_prod_urea_kgN_tree = .58

nw_prod_impact = nw_prod_pesticide_application_ha_tree * imp.pesticide_application_impact_dict + \
    nw_prod_pesticide_kg_tree * imp.pesticide_impact_dict + \
    nw_prod_urea_kgN_tree * imp.urea_impact_dict


#Nut Production
nut_prod_harvester_kg_tree = .45
nut_prod_shaker_kg_tree = .41
nut_prod_sweeper_kg_tree = .38
nut_prod_petrol_harvesting_kg_tree = 20

nut_prod_impact = nut_prod_harvester_kg_tree * imp.unspecified_ag_machinery_impact_dict + \
    nut_prod_shaker_kg_tree * imp.unspecified_ag_machinery_impact_dict + \
    nut_prod_sweeper_kg_tree * imp.unspecified_ag_machinery_impact_dict + \
    nut_prod_petrol_harvesting_kg_tree * imp.petrol_impact_dict

chestnut_prod_impact = nw_prod_impact + nut_prod_impact

#Hay Production
hay_prod_mowing_ha_tree = 1.7
hay_prod_haying_ha_tree = 1.7
hay_prod_baling_p_tree = 8.5
hay_prod_bale_loading_p_tree = 37
hay_prod_petrol_seed_delivery_kg_tree = .2
hay_prod_grass_seed_kg_tree = .25

hay_prod_impact = hay_prod_mowing_ha_tree * imp.mowing_impact_dict + \
    hay_prod_haying_ha_tree * imp.haying_impact_dict + \
    hay_prod_baling_p_tree * imp.baling_impact_dict + \
    hay_prod_bale_loading_p_tree * imp.bale_loading_impact_dict + \
    hay_prod_petrol_seed_delivery_kg_tree * imp.petrol_impact_dict + \
    hay_prod_grass_seed_kg_tree * imp.grass_seed_impact_dict


#Total Production Impact
total_prod_impact = chestnut_prod_impact + hay_prod_impact


#Wood Destruction Impact
wood_dest_harvesting_hr_tree = .033

wood_dest_impact = wood_dest_harvesting_hr_tree * imp.tree_harvesting_impact_dict
total_dest_impact = wood_dest_impact


